#pragma once

// 初始化策略
#define EAS_INIT_STRATEGY_RANDOM    0
#define EAS_INIT_STRATEGY_UNIFORM   1

// 交叉策略
#define EAS_CROSSOVER_STRATEGY_SINGLEPOINT   0
#define EAS_CROSSOVER_STRATEGY_DOUBLEPOINT   1
#define EAS_CROSSOVER_STRATEGY_MULTIPOINT    2
#define EAS_CROSSOVER_STRATEGY_UNIFORM       3
#define EAS_CROSSOVER_STRATEGY_PARTIALMAPPED 4
#define EAS_CROSSOVER_STRATEGY_ORDER         5
#define EAS_CROSSOVER_STRATEGY_CYCLE         6

// 变异策略
#define EAS_MUTATION_STRATEGY_COMMON     0
#define EAS_MUTATION_STRATEGY_EXCHANGE   1
#define EAS_MUTATION_STRATEGY_SHIFT      2
#define EAS_MUTATION_STRATEGY_INSERT     3
#define EAS_MUTATION_STRATEGY_UNIFORM    4
#define EAS_MUTATION_STRATEGY_NORMAL     5
#define EAS_MUTATION_STRATEGY_NO_UNIFORM 6

// 选择策略
#define EAS_CHOOSE_STRATEGY_ROULETTE     0
#define EAS_CHOOSE_STRATEGY_ORDER        1
#define EAS_CHOOSE_STRATEGY_CROWING      2
#define EAS_CHOOSE_STRATEGY_COMPITIVE    3
#define EAS_CHOOSE_STRATEGY_CUSTOM       4


// 其他参数
// 该参数基本不要动，设置的小了之后父代减少，产生的子代更少，导致种群越来越少（类比与现实生活中的生子率，维持1稳定）
#define EAS_CHOOSE_RATE           1.0
// 该参数代表精英保留预留率
#define EAS_CHOOSE_RESERVE_RATE   0.2